[package]
name = "ez"
version = "0.1.0"
edition = "2021"
description = "Eazy to use tweening library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.20.2"

